import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { FieldValues, SubmitHandler, useForm } from "react-hook-form";

import { api } from "~/utils/api";
import Layout from "~/components/layout";
import CreateEditForm from "~/shared/products/components/create-edit-form";

const CreateProductPage: NextPage = () => {
  //   const { data: products } = api.product.getProducts.useQuery();
  const { mutate } = api.product.createProduct.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex  h-full items-center justify-center">
          <CreateEditForm />
        </div>
      </Layout>
    </>
  );
};

export default CreateProductPage;
