import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Layout from "~/components/layout";

const ProductPage: NextPage = () => {
  const { data: products } = api.product.getProducts.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex justify-between pb-14">
          <h1 className="font-bold text-white">Productos</h1>
          <Link
            className="rounded-lg bg-lime-500 px-4 py-2 text-white"
            href="/product/create"
          >
            Crear producto
          </Link>
        </div>

        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-violet-900">
            <tr>
              <th
                scope="col"
                className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-white"
              >
                Nombre
              </th>
              <th
                scope="col"
                className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-white"
              >
                Precio
              </th>
              <th scope="col" className="relative px-6 py-3">
                <span className="sr-only">Editar</span>
              </th>
              <th scope="col" className="relative px-6 py-3">
                <span className="sr-only">Borrar</span>
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 bg-violet-800">
            {products?.map((product) => (
              <tr key={product.id}>
                <td className="whitespace-nowrap px-6 py-4">
                  <div className="text-sm  text-white">{product.name}</div>
                </td>
                <td className="whitespace-nowrap px-6 py-4">
                  <div className="text-sm  text-white">{product.price}</div>
                </td>
                <td className="whitespace-nowrap px-6 py-4 text-right text-sm font-medium">
                  <a
                    href="#"
                    className=" rounded-sm bg-orange-400 px-2 py-1 text-white hover:bg-orange-600"
                  >
                    Editar
                  </a>
                </td>
                <td className="whitespace-nowrap px-6 py-4 text-right text-sm font-medium">
                  <a
                    href="#"
                    className=" rounded-sm bg-red-500 px-2 py-1 text-white hover:bg-red-600"
                  >
                    Borrar
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Layout>
    </>
  );
};

export default ProductPage;
